#!/usr/bin/env python3
"""
tools/agent-guide-bundle.py — snapshot the repository files that the agent
guide's Docs browser lists into html/agent-guide-docs.js.

Why this exists: html/index.html is opened straight from disk (file://), and
browsers block a file:// page from fetching sibling files. The one thing they
do allow is a <script src> from the page's own folder — so the guide loads
this generated file and renders the docs from it. When the page is served over
HTTP it fetches the live files instead and never touches the snapshot.

The file list is read from html/index.html itself (every data-src="../..."
anchor in the Docs browser panel), so there is exactly one registry.

Usage:
  python3 tools/agent-guide-bundle.py             # (re)write the snapshot
  python3 tools/agent-guide-bundle.py --if-stale  # write only if it differs
  python3 tools/agent-guide-bundle.py --check     # exit 1 if missing or stale

tools/conformance-check.py check 6 runs --check; tools/conformance-posttool-hook.sh
runs --if-stale after every governed edit, so the snapshot cannot drift from
its sources without the pre-commit gate noticing.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GUIDE = ROOT / "html" / "index.html"
OUT = ROOT / "html" / "agent-guide-docs.js"
SRC_RE = re.compile(r'data-src="(\.\./[^"]+)"')

HEADER = (
    "// Generated by tools/agent-guide-bundle.py from the files listed in the Docs browser of html/index.html.\n"
    "// Do not edit by hand. Regenerate with: python3 tools/agent-guide-bundle.py\n"
    "// (tools/conformance-posttool-hook.sh regenerates it after every governed edit; conformance check 6 blocks a stale snapshot.)\n"
)


def registry():
    """Ordered, de-duplicated list of the page's data-src paths (relative to html/)."""
    text = GUIDE.read_text(encoding="utf-8")
    seen = []
    for match in SRC_RE.finditer(text):
        if match.group(1) not in seen:
            seen.append(match.group(1))
    return seen


def build():
    files, missing = {}, []
    for rel in registry():
        path = (GUIDE.parent / rel).resolve()
        if not path.is_file():
            missing.append(rel)
            continue
        files[rel] = path.read_text(encoding="utf-8", errors="replace")
    payload = json.dumps({"files": files}, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    # Keep the payload safe even if someone inlines it into HTML, and safe for
    # older JS engines that reject raw U+2028/U+2029 inside string literals.
    payload = payload.replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return HEADER + "window.AGENT_GUIDE_DOCS = " + payload + ";\n", files, missing


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the snapshot is missing or stale; write nothing")
    parser.add_argument("--if-stale", action="store_true", help="write only when the snapshot differs from its sources")
    args = parser.parse_args()

    if not GUIDE.is_file():
        print(f"ERROR: {GUIDE.relative_to(ROOT)} not found", file=sys.stderr)
        return 1
    js, files, missing = build()
    if missing:
        print("ERROR: the Docs browser lists files that do not exist:", file=sys.stderr)
        for rel in missing:
            print(f"  {rel}", file=sys.stderr)
        return 1

    current = OUT.read_text(encoding="utf-8") if OUT.is_file() else None
    rel_out = OUT.relative_to(ROOT).as_posix()
    if args.check:
        if current == js:
            print(f"{rel_out} is in sync with its {len(files)} source files")
            return 0
        state = "missing" if current is None else "stale"
        print(f"{rel_out} is {state} — run: python3 tools/agent-guide-bundle.py")
        return 1
    if args.if_stale and current == js:
        return 0
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {rel_out} — {len(files)} files, {len(js.encode('utf-8')) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
